### PR TITLE
Adding function for calling server with sentences/tokens as input rather than text

### PR DESCRIPTION
**Pull request by sanjayss34**
This PR is intended as a solution for Issue #95

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks, @sanjayss34 

I'm trying to see how does this satisfy #95. What you have added is a sentence-split paragraph, however, what you seemed to want in #95, is annotating a pre-tokenized text.

**Comment by sanjayss34** [comment]
Thanks for your comment @danyaljj The sentences parameter to the new function is supposed to be a list of lists of strings. For instance: [['A', 'dog', 'walked', 'in', 'the', 'park', '.'], ['A', 'cat', 'came', 'later', '.']]. And the function creates a TextAnnotation object by specifying the given tokens and the corresponding character offsets and sentence-end-positions. So this does allow for annotating a pre-tokenized text.

**Comment by danyaljj** [comment]
Ah I see, that makes sense. Can you clarify this in a comment, right before the function, please?

**Comment by sanjayss34** [comment]
I have added more to the doc-string at the beginning of the function. Please let me know if you'd like me to add something else.

**Pull request merged**
